package nl.johnvanweel.iot.light.access.boblight;

import com.sun.jna.Library;
import com.sun.jna.Pointer;

/**
 * Lowlevel interface to the boblight daemon. Implementation generated by JNA.
 */
public interface BoblightDaemon extends Library {
    Pointer boblight_init();

    int boblight_connect(Pointer vpboblight, Pointer address, int port, int usectimeout);

    int boblight_setpriority(Pointer vpboblight, int priority);

    int boblight_getnrlights(Pointer vpboblight);

    int boblight_addpixel(Pointer vpboblight, int lightnr, int[] rgb);

    int boblight_sendrgb(Pointer vpboblight, int sync, int[] outputused);
}
